project:
  type: website
  render:
    - "**/*.qmd"
    - "!posts/2026/04/2026-04-18-ruiz-equilibration.qmd"


website:
  title: "Jason H. Nicholson"
  site-url: "https://jasonhnicholson.com"
  navbar:
    left:
      - blog.qmd
      - text: Pages
        menu:
          - pages/numerical-methods/index.qmd
          - pages/regularizeNd/index.qmd
          - pages/system-identification/index.qmd
      - about.qmd
      
          

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark:
        - darkly
        - brand
      light:
        - cosmo
        - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  cache: true
  daemon: 3600

engines: ['julia']

