---
title: "Jake's command line tools"
date: 2025-12-16
---

I have a coworker named Jake who is a big fan of command line tools. Here some of the tools has recommended and I am learning. Below is a list of tools he recommended.

- [Wezterm](https://github.com/wezterm/wezterm)
  - Modern terminal emulator with multiplex features built in (no need for tmux)
  - [Settings](https://github.com/JakeHandsome/dotfiles/blob/aad557778620eac94b8258d1b9b3be1d13db2550/.config/wezterm/wezterm.lua)
- [Clink](https://github.com/chrisant996/clink)
  - Modern shell for windows, makes using the terminal for finding files or auto completions easy
  - Settings
    - `clink set exec_match_style -1`
      - This lets you autocomplete any file for executables. Allowing you do to `start sln<tab>` and have it auto complete to `start Dune-ADC-Code.sln` which lets me open visual studio from command line (Works for any file type)
    - [Clink completions](https://github.com/vladimir-kotikov/clink-completions) 
        - Adds more completions, importart for git operations
- [Starship](https://github.com/starship/starship)
  - Terminal prompt, gives information related to project right in your shell
  - Settings
    - [Clink integration](https://github.com/JakeHandsome/dotfiles/blob/aad557778620eac94b8258d1b9b3be1d13db2550/clink/starship.lua)
- [Zoxide](https://github.com/ajeetdsouza/zoxide)
    - Smarter cd command, lets you type partial paths and fuzzy find previously visited directories
    - Settings 
      - [Clink integration](https://github.com/JakeHandsome/dotfiles/blob/aad557778620eac94b8258d1b9b3be1d13db2550/clink/zoxide.lua)
- [uutils/coreutils](https://github.com/uutils/coreutils)
    - Rewrite of GNU coreutils in rust, works for windows. Use the same commands on linux and windows
    - Settings
      - [Clink aliases](https://github.com/JakeHandsome/dotfiles/blob/aad557778620eac94b8258d1b9b3be1d13db2550/clink/clink_start.cmd#L5-L7)
- ripgrep (rg) https://github.com/BurntSushi/ripgrep
  - Super fast grep
- [fd](https://github.com/sharkdp/fd)
  - Super fast file find
- [neovim](https://github.com/neovim/neovim)
  - Best editor in Jake's opinion
  - [Settings](https://github.com/JakeHandsome/dotfiles/tree/aad557778620eac94b8258d1b9b3be1d13db2550/nvim) (These are personal and you should probably write your own, A good started config is called LazyVim)
- [Kanata](https://github.com/jtroo/kanata/)
  - Tool for software remapping of keys, I remap CAPSLOCK to ESC to make ESC more reachable
  - [Settings](https://github.com/JakeHandsome/dotfiles/blob/aad557778620eac94b8258d1b9b3be1d13db2550/caps2esc.kbd)
- [gsudo](https://github.com/gerardog/gsudo)
  - Adds sudo to windows, its nice. need to make sure to overwrite the default windows 11 sudo
  - Troubleshooting in win11 https://gerardog.github.io/gsudo/docs/gsudo-vs-sudo#what-if-i-install-both
- [bat](https://github.com/sharkdp/bat)
  - Upgraded cat command, provide some pretty printing and git context when used
- [difftastic](https://github.com/Wilfred/difftastic)
  - Better terminal diff tool (My default git diff command, gitdifftool goes to beyond compare)

