---
title: "Switching to Quarto from Franklin.jl"
date: 2025-11-28
---

After initially migrating to Franklin.jl in the last several weeks, I migrated again to [Quarto](https://quarto.org). Franklin.jl is 
okay but Quarto is better. Here are my reasons migrating:

- Franklin.jl's support of base Markdown features was lacking. In most static site generators, Markdown is a superset of HTML
making the HTML inline with the Markdown. Franklin required `~~~` blocks to signify HTML   blocks. Mixing equations and HTML
together is tricky without inline HTML.
- Franklin.jl does not have built in search support.
- Quarto feels more professional. Less bugs. Less stack traces in the command line or REPL when working with Quarto.
- Franklin.jl's blog support is terrible. I opted for a static blog page in Franklin.jl because I had spent days trying
to hack together the right functions to parse the posts. Quarto's blog functionality worked out of the box.
- More formats. Quarto can generate other formats while Franklin.jl cannot.
- Franklin.jl's prerender and minify didn't always work. As well, adding syntax highlighting for VBA only worked for
local rendering. The prerender was so different that I could not easily hack it to get it to work. I gave up and turned
prerender off.
- Franklin.jl's understanding of image location is site relative and not relative to where the images are on disk. This 
makes VSCode's understanding of location incorrect. 

I migrated from Franklin.jl to Quarto in a day. I started this morning around 10:00 am. In that time, 

- I learned basic Quarto through tutorials.
- Converted 39 .md files to .qmd files.
- Fixed all links and image issues.
- Updated the deploy script.

Thank you Quarto team for a great tool!

Franklin, it's been nice. Goodbye.